name: lor_deck_codes
version: 1.0.7
description: 'The LorDeckCodes library can be used to encode/decode Legends of Runeterra decks to/from simple strings.'
homepage: https://github.com/exts/lor_deckcodes_dart

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  base32: ^2.1.1
  
dev_dependencies:
  test: ^1.21.0